<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>M0DV0IC3.Cli</RootNamespace>
    <AssemblyName>m0dv0ic3-cli</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\M0DV0IC3.Audio\M0DV0IC3.Audio.csproj" />
  </ItemGroup>

</Project>
